### ISSUE TITLE
node v10 Error [ERR_HTTP_HEADERS_SENT]

### ISSUE THREAD

**Issue by AndreTheHunter** [santthosh/aws-es-kibana#47] opened 2018-05-01 05:37 UTC
On node version 10. I get the following error:
```
_http_outgoing.js:481
    throw new ERR_HTTP_HEADERS_SENT('set');
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ClientRequest.setHeader (_http_outgoing.js:481:11)
    at ProxyServer.<anonymous> (/usr/local/lib/node_modules/aws-es-kibana/index.js:175:14)
    at ProxyServer.emit (/usr/local/lib/node_modules/aws-es-kibana/node_modules/eventemitter3/index.js:184:35)
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/aws-es-kibana/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:132:27)
    at ClientRequest.emit (events.js:187:15)
    at ClientRequest.EventEmitter.emit (domain.js:442:20)
    at tickOnSocket (_http_client.js:639:7)
    at onSocketNT (_http_client.js:655:5)
    at process._tickCallback (internal/process/next_tick.js:174:19)
```

On node 9.11.1 it works.
```sh
> n 9
> node --version
v9.11.1
```

**Comment by MdaaaaO** [comment] 2018-05-08 22:09
running into the same issue
`➜  ~ aws-es-kibana --version
1.0.7
➜  ~ node --version
v10.0.0
`

**Comment by chrisdchristo** [comment] 2018-06-06 17:44
same issue here, on node 10+

**Comment by mlem8** [comment] 2018-06-18 20:51
The issue appears to be caused by the request body buffer not being fully initialized before the proxy request is sent. Still not sure why it only affects node v10+. I packaged a fix into the following PR: https://github.com/santthosh/aws-es-kibana/pull/48.

Let me know if it works!

**Comment by santthosh** [comment] 2018-07-05 07:40
Thanks @mlem8, merged. Can you please test with the latest 1.0.8

**Closed by santthosh** 2018-07-05 07:40 UTC
